### ISSUE TITLE
Reorganize the FAQ to prioritize most important & common questions

### ISSUE THREAD

**Issue by addiebarron** [phillycommunitywireless/phillycommunitywireless#55]
We should make the most important and commonly-requested information easy to access quickly. The copy should also be edited to remove unnecessary and duplicated information.

Good questions to prioritize:

- Who are we?
- How does it work?
- Is it secure / user data questions
- Why is it free? Will it always be free? Etc

**Comment by hawc2** [comment]
I discussed with @cmehretab today some work he can do on the FAQ. Part of the problem is we don't have any section headings for the FAQ organizing the questions into topics. Let's plan to use the four questions @addiebarron outlines here as the main sections for the FAQ. 

A few related issues we should focus on clarifying within the categories Addie defined:
- Quality of internet service
- Related services we can provide (like training, computer procuration)
- Privacy policy (both on the network, and with the community members hosting kits)
- Security (best practices for using public wifi)

It also just seems we need to find a better way to define our project. We're not a municipal wifi network, we're not an ISP. We're a work-in-progress community network built on top of a net-neutral WISP with funding support from the city and nonprofit organizations. Emphasizing the 'cooperative' nature of the network, and how we can help our neighbors, is the nuanced thing we should try to weave through it in this round of edits

**Comment by hawc2** [comment]
@addiebarron I took a shot at reorganizing and refining it. I haven't yet fleshed out many answers yet, which I think could help as well. Perhaps we can also do more internal and external linking of related resources? Like what's a good intro on how to use VPN to be more secure on a public network? Things like that...
